variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

test:pytest:python3-6:
  image: python:3.6
  script:
    - pip install pytest --quiet
    - python -m pytest

test:pytest:python3-7:
  image: python:3.7
  script:
    - pip install pytest --quiet
    - python -m pytest

test:pytest:python3-8:
  image: python:3.8
  script:
    - pip install pytest --quiet
    - python -m pytest

test:pytest:python3-9:
  image: python:3.9
  script:
    - pip install pytest --quiet
    - python -m pytest
