variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

.common_test_template_script: &common_test_template_script
  script:
    - pip install pytest --quiet
    - python -m pytest

test:pytest:python3-8:
  image: python:3.8
  <<: *common_test_template_script

test:pytest:python3-9:
  image: python:3.9
  <<: *common_test_template_script

test:pytest:python3-10:
  image: python:3.10
  <<: *common_test_template_script

#test:pytest:python3-11-release-candidate:
#  image: python:3.11-rc
#  <<: *common_test_template_script
